# Generated by Django 4.1.3 on 2022-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QID', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('duration', models.TimeField()),
            ],
        ),
    ]
