# Generated by Django 4.1.3 on 2022-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_question_question_txt_alter_question_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=6),
        ),
    ]
