# Generated by Django 4.1.3 on 2022-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_question_qid_alter_question_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_txt',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
