# Generated by Django 3.1.7 on 2022-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_rename_question_txt_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
