# Generated by Django 3.1.7 on 2022-11-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAns',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='deptID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='bank.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='programID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prg', to='bank.program'),
        ),
    ]
