# Generated by Django 4.1.3 on 2022-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_department_id_alter_program_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.IntegerField(blank=True, default=0, max_length=100),
            preserve_default=False,
        ),
    ]
