# Generated by Django 3.1.7 on 2022-11-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20221130_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctAns',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
