# Generated by Django 3.1.7 on 2022-12-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_user_password'),
        ('bank', '0013_auto_20221130_0011'),
    ]

    operations = [
    ]
