# Generated by Django 3.1.7 on 2022-12-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=6)),
                ('secNo', models.IntegerField(max_length=2)),
                ('year', models.IntegerField(default=2022)),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_id', to='bank.faculty')),
            ],
        ),
    ]
