# Generated by Django 4.1.3 on 2022-12-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='CourseOutline',
        ),
    ]
