# Generated by Django 3.1.7 on 2022-12-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20221202_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='FUserID',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=6, unique=True)),
                ('courseName', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=5)),
                ('course_deptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_dep', to='bank.department')),
                ('programID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prog', to='bank.program')),
            ],
        ),
    ]
