# Generated by Django 3.1.7 on 2022-12-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_auto_20221202_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='CourseID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sec_courseid', to='bank.course'),
            preserve_default=False,
        ),
    ]
