# Generated by Django 4.1.3 on 2022-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_rename_assesment_courseoutline_assesment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='grading',
            field=models.FloatField(max_length=5),
        ),
    ]
