# Generated by Django 3.1.7 on 2022-12-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_co'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co',
            name='CONo',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='co',
            name='Statement',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='PLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLONo', models.CharField(max_length=4, unique=True)),
                ('PLOTitle', models.TextField(max_length=50)),
                ('PLODescription', models.TextField(max_length=500)),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_prog', to='bank.program')),
            ],
        ),
    ]
