# Generated by Django 4.1.3 on 2022-12-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_alter_courseoutline_grading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='assesment',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='courseResource',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='grading',
            field=models.TextField(max_length=100),
        ),
    ]
