# Generated by Django 3.1.7 on 2022-12-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_alter_courseoutline_assesment_and_more'),
        ('bank', '0022_auto_20221202_2300'),
    ]

    operations = [
    ]
