# Generated by Django 3.1.7 on 2022-12-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_auto_20221202_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutline',
            name='semester',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
