# Generated by Django 3.1.7 on 2022-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_question_course_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAns',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
