# Generated by Django 3.1.7 on 2022-12-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0030_question_correctans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
    ]
