# Generated by Django 4.1.3 on 2022-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_rename_course_q_question_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correctAns',
        ),
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
