# Generated by Django 4.1.3 on 2022-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0034_remove_question_correctans_alter_question_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutline',
            name='course_descrip',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='days',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='mark',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='mob',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='office',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
