# Generated by Django 4.1.3 on 2022-12-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0036_remove_plo_programid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co',
            name='SecID',
        ),
    ]
