# Generated by Django 4.1.3 on 2022-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0038_co_out_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='co',
            name='Domain',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
