# Generated by Django 4.1.3 on 2022-12-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0041_alter_courseoutline_assesment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co',
            name='Domain',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='email',
            field=models.TextField(),
        ),
    ]
