# Generated by Django 4.1.3 on 2022-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0042_alter_co_domain_alter_courseoutline_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='courseCode',
            field=models.CharField(max_length=20),
        ),
    ]
