# Generated by Django 4.1.3 on 2022-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0044_alter_answer_ans_alter_question_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.FloatField(),
        ),
    ]
