# Generated by Django 4.1.3 on 2022-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0048_alter_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_ID',
            field=models.TextField(),
        ),
    ]
