# Generated by Django 4.1.3 on 2022-12-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0049_alter_question_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.IntegerField(),
        ),
    ]
