# Generated by Django 4.1.3 on 2022-12-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0050_alter_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='q_course', to='bank.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=0.0),
        ),
    ]
