# Generated by Django 4.1.3 on 2022-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0051_alter_question_course_id_alter_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
