# Generated by Django 4.1.3 on 2022-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0053_alter_answer_ans_alter_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
